# Site settings
title: ABBY
baseurl: "slim/"
url: "https://ab12gu.github.io/"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
