# Site settings
title: Abhay Gupta
baseurl:
url: "abgup.com"


# Build settings
kramdown:
  input: GFM
permalink: none

# Third-party services
# just leave blank to disable it
google_analytics:
disqus_shortname:

# Personal/Academic Project Folder
collections:
  my_collections:
    output: true
    permalink: /:name 
