# Site settings
title: Abhay Gupta || Mechanical Engineer
baseurl: ""
url: "http://abgup.me"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
