# Site settings
title: Abhay Gupta || Mechanical Engineer
baseurl: ""
url: "https://ab12gu.github.io/Portfolio/"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
