# Site settings
title: Abhay's Portfolio
baseurl: 
url: "abgup.me"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
